// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: product-proto/proto/product.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Product message (maps from your MongoDB document)
type Product struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Use string for MongoDB ObjectId
	Id               string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ShortDescription string   `protobuf:"bytes,3,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	Description      string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price            float64  `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Sizes            []string `protobuf:"bytes,6,rep,name=sizes,proto3" json:"sizes,omitempty"`
	Colors           []string `protobuf:"bytes,7,rep,name=colors,proto3" json:"colors,omitempty"`
	// color -> image path/url
	Images        map[string]string `protobuf:"bytes,8,rep,name=images,proto3" json:"images,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tag           string            `protobuf:"bytes,9,opt,name=tag,proto3" json:"tag,omitempty"`
	Band          string            `protobuf:"bytes,10,opt,name=band,proto3" json:"band,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_proto_proto_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_proto_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_proto_proto_product_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetSizes() []string {
	if x != nil {
		return x.Sizes
	}
	return nil
}

func (x *Product) GetColors() []string {
	if x != nil {
		return x.Colors
	}
	return nil
}

func (x *Product) GetImages() map[string]string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Product) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Product) GetBand() string {
	if x != nil {
		return x.Band
	}
	return ""
}

type CreateProductRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// supply the product without an id (server usually assigns)
	Product       *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_product_proto_proto_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_proto_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_proto_product_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductRequest) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_product_proto_proto_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_proto_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_proto_product_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type GetProductByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductByIdRequest) Reset() {
	*x = GetProductByIdRequest{}
	mi := &file_product_proto_proto_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductByIdRequest) ProtoMessage() {}

func (x *GetProductByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_proto_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductByIdRequest.ProtoReflect.Descriptor instead.
func (*GetProductByIdRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_proto_product_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProductByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductByIdResponse) Reset() {
	*x = GetProductByIdResponse{}
	mi := &file_product_proto_proto_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductByIdResponse) ProtoMessage() {}

func (x *GetProductByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_proto_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductByIdResponse.ProtoReflect.Descriptor instead.
func (*GetProductByIdResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_proto_product_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductByIdResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type UpdateProductByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Product       *Product               `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductByIdRequest) Reset() {
	*x = UpdateProductByIdRequest{}
	mi := &file_product_proto_proto_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductByIdRequest) ProtoMessage() {}

func (x *UpdateProductByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_proto_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductByIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductByIdRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_proto_product_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProductByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProductByIdRequest) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type UpdateProductByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductByIdResponse) Reset() {
	*x = UpdateProductByIdResponse{}
	mi := &file_product_proto_proto_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductByIdResponse) ProtoMessage() {}

func (x *UpdateProductByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_proto_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductByIdResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductByIdResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_proto_product_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProductByIdResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteProductByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductByIdRequest) Reset() {
	*x = DeleteProductByIdRequest{}
	mi := &file_product_proto_proto_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductByIdRequest) ProtoMessage() {}

func (x *DeleteProductByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_proto_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductByIdRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_proto_product_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProductByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteProductByIdResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optionally return the deleted id or empty
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductByIdResponse) Reset() {
	*x = DeleteProductByIdResponse{}
	mi := &file_product_proto_proto_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductByIdResponse) ProtoMessage() {}

func (x *DeleteProductByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_proto_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductByIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductByIdResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_proto_product_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteProductByIdResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListProductsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional simple pagination
	PageSize  int32  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional filter by tag or band (simple examples)
	Tag           string `protobuf:"bytes,10,opt,name=tag,proto3" json:"tag,omitempty"`
	Band          string `protobuf:"bytes,11,opt,name=band,proto3" json:"band,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_product_proto_proto_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_proto_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_proto_product_proto_rawDescGZIP(), []int{9}
}

func (x *ListProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListProductsRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ListProductsRequest) GetBand() string {
	if x != nil {
		return x.Band
	}
	return ""
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_product_proto_proto_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_proto_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_proto_product_proto_rawDescGZIP(), []int{10}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_product_proto_proto_product_proto protoreflect.FileDescriptor

const file_product_proto_proto_product_proto_rawDesc = "" +
	"\n" +
	"!product-proto/proto/product.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xcf\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\x11short_description\x18\x03 \x01(\tR\x10shortDescription\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x14\n" +
	"\x05sizes\x18\x06 \x03(\tR\x05sizes\x12\x16\n" +
	"\x06colors\x18\a \x03(\tR\x06colors\x12,\n" +
	"\x06images\x18\b \x03(\v2\x14.Product.ImagesEntryR\x06images\x12\x10\n" +
	"\x03tag\x18\t \x01(\tR\x03tag\x12\x12\n" +
	"\x04band\x18\n" +
	" \x01(\tR\x04band\x1a9\n" +
	"\vImagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x14CreateProductRequest\x12\"\n" +
	"\aproduct\x18\x01 \x01(\v2\b.ProductR\aproduct\";\n" +
	"\x15CreateProductResponse\x12\"\n" +
	"\aproduct\x18\x01 \x01(\v2\b.ProductR\aproduct\"'\n" +
	"\x15GetProductByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x16GetProductByIdResponse\x12\"\n" +
	"\aproduct\x18\x01 \x01(\v2\b.ProductR\aproduct\"N\n" +
	"\x18UpdateProductByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\aproduct\x18\x02 \x01(\v2\b.ProductR\aproduct\"5\n" +
	"\x19UpdateProductByIdResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\x18DeleteProductByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x19DeleteProductByIdResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"w\n" +
	"\x13ListProductsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x10\n" +
	"\x03tag\x18\n" +
	" \x01(\tR\x03tag\x12\x12\n" +
	"\x04band\x18\v \x01(\tR\x04band\"d\n" +
	"\x14ListProductsResponse\x12$\n" +
	"\bproducts\x18\x01 \x03(\v2\b.ProductR\bproducts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xf6\x05\n" +
	"\x0eProductService\x12\xa3\x01\n" +
	"\rCreateProduct\x12\x15.CreateProductRequest\x1a\x16.CreateProductResponse\"c\x92AF\x12\x14Create a new product\x1a\x1cRequires JWT authentication.b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x14:\aproduct\"\t/products\x12o\n" +
	"\x0eGetProductById\x12\x16.GetProductByIdRequest\x1a\x17.GetProductByIdResponse\",\x92A\x13\x12\x11Get product by ID\x82\xd3\xe4\x93\x02\x10\x12\x0e/products/{id}\x12\xba\x01\n" +
	"\x11UpdateProductById\x12\x19.UpdateProductByIdRequest\x1a\x1a.UpdateProductByIdResponse\"n\x92AL\x12\x1aUpdate an existing product\x1a\x1cRequires JWT authentication.b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x19:\aproduct\x1a\x0e/products/{id}\x12\xad\x01\n" +
	"\x11DeleteProductById\x12\x19.DeleteProductByIdRequest\x1a\x1a.DeleteProductByIdResponse\"a\x92AH\x12\x16Delete a product by ID\x1a\x1cRequires JWT authentication.b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x10*\x0e/products/{id}\x12`\n" +
	"\fListProducts\x12\x14.ListProductsRequest\x1a\x15.ListProductsResponse\"#\x92A\x0f\x12\rList products\x82\xd3\xe4\x93\x02\v\x12\t/productsB\xa8\x01\x92A\x9e\x01\x12D\n" +
	"\x13Product Service API\x12(This service handles product management.2\x031.0ZV\n" +
	"T\n" +
	"\n" +
	"BearerAuth\x12F\b\x02\x121JWT Authorization header using the Bearer scheme.\x1a\rAuthorization \x02Z\x04.;pbb\x06proto3"

var (
	file_product_proto_proto_product_proto_rawDescOnce sync.Once
	file_product_proto_proto_product_proto_rawDescData []byte
)

func file_product_proto_proto_product_proto_rawDescGZIP() []byte {
	file_product_proto_proto_product_proto_rawDescOnce.Do(func() {
		file_product_proto_proto_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_proto_product_proto_rawDesc), len(file_product_proto_proto_product_proto_rawDesc)))
	})
	return file_product_proto_proto_product_proto_rawDescData
}

var file_product_proto_proto_product_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_product_proto_proto_product_proto_goTypes = []any{
	(*Product)(nil),                   // 0: Product
	(*CreateProductRequest)(nil),      // 1: CreateProductRequest
	(*CreateProductResponse)(nil),     // 2: CreateProductResponse
	(*GetProductByIdRequest)(nil),     // 3: GetProductByIdRequest
	(*GetProductByIdResponse)(nil),    // 4: GetProductByIdResponse
	(*UpdateProductByIdRequest)(nil),  // 5: UpdateProductByIdRequest
	(*UpdateProductByIdResponse)(nil), // 6: UpdateProductByIdResponse
	(*DeleteProductByIdRequest)(nil),  // 7: DeleteProductByIdRequest
	(*DeleteProductByIdResponse)(nil), // 8: DeleteProductByIdResponse
	(*ListProductsRequest)(nil),       // 9: ListProductsRequest
	(*ListProductsResponse)(nil),      // 10: ListProductsResponse
	nil,                               // 11: Product.ImagesEntry
}
var file_product_proto_proto_product_proto_depIdxs = []int32{
	11, // 0: Product.images:type_name -> Product.ImagesEntry
	0,  // 1: CreateProductRequest.product:type_name -> Product
	0,  // 2: CreateProductResponse.product:type_name -> Product
	0,  // 3: GetProductByIdResponse.product:type_name -> Product
	0,  // 4: UpdateProductByIdRequest.product:type_name -> Product
	0,  // 5: ListProductsResponse.products:type_name -> Product
	1,  // 6: ProductService.CreateProduct:input_type -> CreateProductRequest
	3,  // 7: ProductService.GetProductById:input_type -> GetProductByIdRequest
	5,  // 8: ProductService.UpdateProductById:input_type -> UpdateProductByIdRequest
	7,  // 9: ProductService.DeleteProductById:input_type -> DeleteProductByIdRequest
	9,  // 10: ProductService.ListProducts:input_type -> ListProductsRequest
	2,  // 11: ProductService.CreateProduct:output_type -> CreateProductResponse
	4,  // 12: ProductService.GetProductById:output_type -> GetProductByIdResponse
	6,  // 13: ProductService.UpdateProductById:output_type -> UpdateProductByIdResponse
	8,  // 14: ProductService.DeleteProductById:output_type -> DeleteProductByIdResponse
	10, // 15: ProductService.ListProducts:output_type -> ListProductsResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_product_proto_proto_product_proto_init() }
func file_product_proto_proto_product_proto_init() {
	if File_product_proto_proto_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_proto_product_proto_rawDesc), len(file_product_proto_proto_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_proto_product_proto_goTypes,
		DependencyIndexes: file_product_proto_proto_product_proto_depIdxs,
		MessageInfos:      file_product_proto_proto_product_proto_msgTypes,
	}.Build()
	File_product_proto_proto_product_proto = out.File
	file_product_proto_proto_product_proto_goTypes = nil
	file_product_proto_proto_product_proto_depIdxs = nil
}
