// Use proto3 syntax for modern features and Go-friendly code generation.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: user-proto/proto/user.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The core data model for a User.
// Field numbers (1, 2, 3...) are unique identifiers and should never be changed.
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ObjectID as hex string
	Firstname     string                 `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname      string                 `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Accesskey     string                 `protobuf:"bytes,6,opt,name=accesskey,proto3" json:"accesskey,omitempty"`
	Isactive      bool                   `protobuf:"varint,7,opt,name=isactive,proto3" json:"isactive,omitempty"`
	Createby      string                 `protobuf:"bytes,8,opt,name=createby,proto3" json:"createby,omitempty"`
	Createdat     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=createdat,proto3" json:"createdat,omitempty"`
	Updateby      string                 `protobuf:"bytes,10,opt,name=updateby,proto3" json:"updateby,omitempty"`
	Updatedat     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updatedat,proto3" json:"updatedat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *User) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetAccesskey() string {
	if x != nil {
		return x.Accesskey
	}
	return ""
}

func (x *User) GetIsactive() bool {
	if x != nil {
		return x.Isactive
	}
	return false
}

func (x *User) GetCreateby() string {
	if x != nil {
		return x.Createby
	}
	return ""
}

func (x *User) GetCreatedat() *timestamppb.Timestamp {
	if x != nil {
		return x.Createdat
	}
	return nil
}

func (x *User) GetUpdateby() string {
	if x != nil {
		return x.Updateby
	}
	return ""
}

func (x *User) GetUpdatedat() *timestamppb.Timestamp {
	if x != nil {
		return x.Updatedat
	}
	return nil
}

// Request message for creating a new user.
// We include the raw password here as it will be hashed by the server.
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_proto_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Response message after a user is created.
// It returns the newly created User object.
type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_user_proto_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Request message for getting a user by their ID.
type GetUserByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdRequest) Reset() {
	*x = GetUserByIdRequest{}
	mi := &file_user_proto_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdRequest) ProtoMessage() {}

func (x *GetUserByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserByIdRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Response message for getting a user.
type GetUserByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdResponse) Reset() {
	*x = GetUserByIdResponse{}
	mi := &file_user_proto_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdResponse) ProtoMessage() {}

func (x *GetUserByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIdResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserByIdResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Request message for updating an existing user.
// We use a separate message to allow for partial updates.
// For example, if you only want to update the email, you don't
// need to send the other fields.
type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // ObjectID as hex string
	User          *UserUpdate            `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"` // this will go in the JSON body
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_proto_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetUser() *UserUpdate {
	if x != nil {
		return x.User
	}
	return nil
}

type UserUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Firstname     string                 `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname      string                 `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Accesskey     string                 `protobuf:"bytes,5,opt,name=accesskey,proto3" json:"accesskey,omitempty"`
	Updatedby     string                 `protobuf:"bytes,6,opt,name=updatedby,proto3" json:"updatedby,omitempty"`
	Updatedat     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updatedat,proto3" json:"updatedat,omitempty"`
	Isactive      bool                   `protobuf:"varint,8,opt,name=isactive,proto3" json:"isactive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdate) Reset() {
	*x = UserUpdate{}
	mi := &file_user_proto_proto_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdate) ProtoMessage() {}

func (x *UserUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_proto_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdate.ProtoReflect.Descriptor instead.
func (*UserUpdate) Descriptor() ([]byte, []int) {
	return file_user_proto_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserUpdate) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *UserUpdate) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *UserUpdate) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserUpdate) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserUpdate) GetAccesskey() string {
	if x != nil {
		return x.Accesskey
	}
	return ""
}

func (x *UserUpdate) GetUpdatedby() string {
	if x != nil {
		return x.Updatedby
	}
	return ""
}

func (x *UserUpdate) GetUpdatedat() *timestamppb.Timestamp {
	if x != nil {
		return x.Updatedat
	}
	return nil
}

func (x *UserUpdate) GetIsactive() bool {
	if x != nil {
		return x.Isactive
	}
	return false
}

// Response message after a user is updated.
type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_user_proto_proto_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_proto_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Request message for list users.
type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_user_proto_proto_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_proto_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_proto_user_proto_rawDescGZIP(), []int{8}
}

// Response message for list users.
type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_user_proto_proto_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_proto_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_proto_user_proto_rawDescGZIP(), []int{9}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

// Request message for delete user.
type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ObjectID as hex string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_user_proto_proto_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_proto_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_proto_user_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response message for list users.
type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_user_proto_proto_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_proto_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_proto_user_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UserActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ObjectID as hex string
	Firstname     string                 `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname      string                 `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Accesskey     string                 `protobuf:"bytes,6,opt,name=accesskey,proto3" json:"accesskey,omitempty"`
	Isactive      bool                   `protobuf:"varint,7,opt,name=isactive,proto3" json:"isactive,omitempty"`
	Module        string                 `protobuf:"bytes,8,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserActionRequest) Reset() {
	*x = UserActionRequest{}
	mi := &file_user_proto_proto_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserActionRequest) ProtoMessage() {}

func (x *UserActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_proto_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserActionRequest.ProtoReflect.Descriptor instead.
func (*UserActionRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_proto_user_proto_rawDescGZIP(), []int{12}
}

func (x *UserActionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserActionRequest) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *UserActionRequest) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *UserActionRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserActionRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserActionRequest) GetAccesskey() string {
	if x != nil {
		return x.Accesskey
	}
	return ""
}

func (x *UserActionRequest) GetIsactive() bool {
	if x != nil {
		return x.Isactive
	}
	return false
}

func (x *UserActionRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

type UserActionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*UserActionResponse_Login
	//	*UserActionResponse_Register
	Result        isUserActionResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserActionResponse) Reset() {
	*x = UserActionResponse{}
	mi := &file_user_proto_proto_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserActionResponse) ProtoMessage() {}

func (x *UserActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_proto_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserActionResponse.ProtoReflect.Descriptor instead.
func (*UserActionResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_proto_user_proto_rawDescGZIP(), []int{13}
}

func (x *UserActionResponse) GetResult() isUserActionResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UserActionResponse) GetLogin() *LoginResponse {
	if x != nil {
		if x, ok := x.Result.(*UserActionResponse_Login); ok {
			return x.Login
		}
	}
	return nil
}

func (x *UserActionResponse) GetRegister() *CreateUserResponse {
	if x != nil {
		if x, ok := x.Result.(*UserActionResponse_Register); ok {
			return x.Register
		}
	}
	return nil
}

type isUserActionResponse_Result interface {
	isUserActionResponse_Result()
}

type UserActionResponse_Login struct {
	Login *LoginResponse `protobuf:"bytes,1,opt,name=login,proto3,oneof"`
}

type UserActionResponse_Register struct {
	Register *CreateUserResponse `protobuf:"bytes,2,opt,name=register,proto3,oneof"`
}

func (*UserActionResponse_Login) isUserActionResponse_Result() {}

func (*UserActionResponse_Register) isUserActionResponse_Result() {}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_user_proto_proto_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_proto_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_proto_user_proto_rawDescGZIP(), []int{14}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_proto_proto_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_proto_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_proto_user_proto_rawDescGZIP(), []int{15}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"` // refresh token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_proto_proto_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_proto_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_proto_user_proto_rawDescGZIP(), []int{16}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_user_proto_proto_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_proto_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_user_proto_proto_user_proto_rawDescGZIP(), []int{17}
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userid        string                 `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Firstname     string                 `protobuf:"bytes,3,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname      string                 `protobuf:"bytes,4,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_user_proto_proto_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_proto_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_proto_user_proto_rawDescGZIP(), []int{18}
}

func (x *AuthResponse) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *AuthResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthResponse) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *AuthResponse) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *AuthResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_user_proto_proto_user_proto protoreflect.FileDescriptor

const file_user_proto_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x1buser-proto/proto/user.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xe8\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tfirstname\x18\x02 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x03 \x01(\tR\blastname\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x1c\n" +
	"\taccesskey\x18\x06 \x01(\tR\taccesskey\x12\x1a\n" +
	"\bisactive\x18\a \x01(\bR\bisactive\x12\x1a\n" +
	"\bcreateby\x18\b \x01(\tR\bcreateby\x128\n" +
	"\tcreatedat\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedat\x12\x1a\n" +
	"\bupdateby\x18\n" +
	" \x01(\tR\bupdateby\x128\n" +
	"\tupdatedat\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedat\".\n" +
	"\x11CreateUserRequest\x12\x19\n" +
	"\x04user\x18\x01 \x01(\v2\x05.UserR\x04user\"/\n" +
	"\x12CreateUserResponse\x12\x19\n" +
	"\x04user\x18\x01 \x01(\v2\x05.UserR\x04user\":\n" +
	"\x12GetUserByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"0\n" +
	"\x13GetUserByIdResponse\x12\x19\n" +
	"\x04user\x18\x01 \x01(\v2\x05.UserR\x04user\"D\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\x04user\x18\x02 \x01(\v2\v.UserUpdateR\x04user\"\x8a\x02\n" +
	"\n" +
	"UserUpdate\x12\x1c\n" +
	"\tfirstname\x18\x01 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x02 \x01(\tR\blastname\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1c\n" +
	"\taccesskey\x18\x05 \x01(\tR\taccesskey\x12\x1c\n" +
	"\tupdatedby\x18\x06 \x01(\tR\tupdatedby\x128\n" +
	"\tupdatedat\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedat\x12\x1a\n" +
	"\bisactive\x18\b \x01(\bR\bisactive\".\n" +
	"\x12UpdateUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x12\n" +
	"\x10ListUsersRequest\"0\n" +
	"\x11ListUsersResponse\x12\x1b\n" +
	"\x05users\x18\x01 \x03(\v2\x05.UserR\x05users\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xe1\x01\n" +
	"\x11userActionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tfirstname\x18\x02 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x03 \x01(\tR\blastname\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x1c\n" +
	"\taccesskey\x18\x06 \x01(\tR\taccesskey\x12\x1a\n" +
	"\bisactive\x18\a \x01(\bR\bisactive\x12\x16\n" +
	"\x06module\x18\b \x01(\tR\x06module\"y\n" +
	"\x12UserActionResponse\x12&\n" +
	"\x05login\x18\x01 \x01(\v2\x0e.LoginResponseH\x00R\x05login\x121\n" +
	"\bregister\x18\x02 \x01(\v2\x13.CreateUserResponseH\x00R\bregisterB\b\n" +
	"\x06result\"4\n" +
	"\x0eRefreshRequest\x12\"\n" +
	"\frefreshToken\x18\x01 \x01(\tR\frefreshToken\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"I\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\"\a\n" +
	"\x05Empty\"\x8a\x01\n" +
	"\fAuthResponse\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\tR\x06userid\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1c\n" +
	"\tfirstname\x18\x03 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x04 \x01(\tR\blastname\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role2\x88\b\n" +
	"\vUserService\x12\x90\x01\n" +
	"\vGetUserById\x12\x13.GetUserByIdRequest\x1a\x14.GetUserByIdResponse\"V\x92A@\x12\x0eGet user by ID\x1a\x1cRequires JWT authentication.b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\r\x12\v/users/{id}\x12\x90\x01\n" +
	"\n" +
	"UpdateUser\x12\x12.UpdateUserRequest\x1a\x13.UpdateUserResponse\"Y\x92A=\x12\vUpdate user\x1a\x1cRequires JWT authentication.b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x13:\x04user\x1a\v/users/{id}\x12\x81\x01\n" +
	"\tListUsers\x12\x11.ListUsersRequest\x1a\x12.ListUsersResponse\"M\x92A<\x12\n" +
	"List users\x1a\x1cRequires JWT authentication.b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\b\x12\x06/users\x12\x8a\x01\n" +
	"\n" +
	"DeleteUser\x12\x12.DeleteUserRequest\x1a\x13.DeleteUserResponse\"S\x92A=\x12\vDelete user\x1a\x1cRequires JWT authentication.b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\r*\v/users/{id}\x12\x9a\x01\n" +
	"\n" +
	"CreateUser\x12\x12.CreateUserRequest\x1a\x13.CreateUserResponse\"c\x92AF\x12\x14Create/Register user\x1a\x1cRequires JWT authentication.b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/users/register\x12z\n" +
	"\aGetUser\x12\x06.Empty\x1a\r.AuthResponse\"X\x92AD\x120Retrieve the currently authenticated user's datab\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\v\x12\t/users/me\x12f\n" +
	"\tLoginUser\x12\r.LoginRequest\x1a\x0e.LoginResponse\":\x92A \x12\x1eUser login (no authentication)\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/users/login\x12A\n" +
	"\fRefreshToken\x12\x0f.RefreshRequest\x1a\x0e.LoginResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\"\b/refreshB\xa2\x01\x92A\x98\x01\x12>\n" +
	"\x10User Service API\x12%This service handles user management.2\x031.0ZV\n" +
	"T\n" +
	"\n" +
	"BearerAuth\x12F\b\x02\x121JWT Authorization header using the Bearer scheme.\x1a\rAuthorization \x02Z\x04.;pbb\x06proto3"

var (
	file_user_proto_proto_user_proto_rawDescOnce sync.Once
	file_user_proto_proto_user_proto_rawDescData []byte
)

func file_user_proto_proto_user_proto_rawDescGZIP() []byte {
	file_user_proto_proto_user_proto_rawDescOnce.Do(func() {
		file_user_proto_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_proto_user_proto_rawDesc), len(file_user_proto_proto_user_proto_rawDesc)))
	})
	return file_user_proto_proto_user_proto_rawDescData
}

var file_user_proto_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_user_proto_proto_user_proto_goTypes = []any{
	(*User)(nil),                  // 0: User
	(*CreateUserRequest)(nil),     // 1: CreateUserRequest
	(*CreateUserResponse)(nil),    // 2: CreateUserResponse
	(*GetUserByIdRequest)(nil),    // 3: GetUserByIdRequest
	(*GetUserByIdResponse)(nil),   // 4: GetUserByIdResponse
	(*UpdateUserRequest)(nil),     // 5: UpdateUserRequest
	(*UserUpdate)(nil),            // 6: UserUpdate
	(*UpdateUserResponse)(nil),    // 7: UpdateUserResponse
	(*ListUsersRequest)(nil),      // 8: ListUsersRequest
	(*ListUsersResponse)(nil),     // 9: ListUsersResponse
	(*DeleteUserRequest)(nil),     // 10: DeleteUserRequest
	(*DeleteUserResponse)(nil),    // 11: DeleteUserResponse
	(*UserActionRequest)(nil),     // 12: userActionRequest
	(*UserActionResponse)(nil),    // 13: UserActionResponse
	(*RefreshRequest)(nil),        // 14: RefreshRequest
	(*LoginRequest)(nil),          // 15: LoginRequest
	(*LoginResponse)(nil),         // 16: LoginResponse
	(*Empty)(nil),                 // 17: Empty
	(*AuthResponse)(nil),          // 18: AuthResponse
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
}
var file_user_proto_proto_user_proto_depIdxs = []int32{
	19, // 0: User.createdat:type_name -> google.protobuf.Timestamp
	19, // 1: User.updatedat:type_name -> google.protobuf.Timestamp
	0,  // 2: CreateUserRequest.user:type_name -> User
	0,  // 3: CreateUserResponse.user:type_name -> User
	0,  // 4: GetUserByIdResponse.user:type_name -> User
	6,  // 5: UpdateUserRequest.user:type_name -> UserUpdate
	19, // 6: UserUpdate.updatedat:type_name -> google.protobuf.Timestamp
	0,  // 7: ListUsersResponse.users:type_name -> User
	16, // 8: UserActionResponse.login:type_name -> LoginResponse
	2,  // 9: UserActionResponse.register:type_name -> CreateUserResponse
	3,  // 10: UserService.GetUserById:input_type -> GetUserByIdRequest
	5,  // 11: UserService.UpdateUser:input_type -> UpdateUserRequest
	8,  // 12: UserService.ListUsers:input_type -> ListUsersRequest
	10, // 13: UserService.DeleteUser:input_type -> DeleteUserRequest
	1,  // 14: UserService.CreateUser:input_type -> CreateUserRequest
	17, // 15: UserService.GetUser:input_type -> Empty
	15, // 16: UserService.LoginUser:input_type -> LoginRequest
	14, // 17: UserService.RefreshToken:input_type -> RefreshRequest
	4,  // 18: UserService.GetUserById:output_type -> GetUserByIdResponse
	7,  // 19: UserService.UpdateUser:output_type -> UpdateUserResponse
	9,  // 20: UserService.ListUsers:output_type -> ListUsersResponse
	11, // 21: UserService.DeleteUser:output_type -> DeleteUserResponse
	2,  // 22: UserService.CreateUser:output_type -> CreateUserResponse
	18, // 23: UserService.GetUser:output_type -> AuthResponse
	16, // 24: UserService.LoginUser:output_type -> LoginResponse
	16, // 25: UserService.RefreshToken:output_type -> LoginResponse
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_user_proto_proto_user_proto_init() }
func file_user_proto_proto_user_proto_init() {
	if File_user_proto_proto_user_proto != nil {
		return
	}
	file_user_proto_proto_user_proto_msgTypes[13].OneofWrappers = []any{
		(*UserActionResponse_Login)(nil),
		(*UserActionResponse_Register)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_proto_user_proto_rawDesc), len(file_user_proto_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_proto_user_proto_goTypes,
		DependencyIndexes: file_user_proto_proto_user_proto_depIdxs,
		MessageInfos:      file_user_proto_proto_user_proto_msgTypes,
	}.Build()
	File_user_proto_proto_user_proto = out.File
	file_user_proto_proto_user_proto_goTypes = nil
	file_user_proto_proto_user_proto_depIdxs = nil
}
